"""leetcode website-solve schema

Schema for the new /leet feature: ``leetcode_links`` (verified Discord<->LeetCode
account), ``leetcode_assignments`` (per-session problem + lifecycle),
``leetcode_role_grants`` (active timed reward-role grants), two ``guild_config``
columns (designated channel + reward role), and three ``users`` columns
(solved total, streak, last solve date) that feed the rank card. The NOT NULL
``users`` columns ship a ``server_default`` of 0 so the populated table backfills
cleanly with no manual step.

Revision ID: 0a4cac82120a
Revises: 2f91223b2f70
Create Date: 2026-06-03 14:34:08.410235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4cac82120a'
down_revision: Union[str, Sequence[str], None] = '2f91223b2f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('problem_title', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leetcode_assignments_discord_user_id'), 'leetcode_assignments', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_leetcode_assignments_guild_id'), 'leetcode_assignments', ['guild_id'], unique=False)
    op.create_table('leetcode_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('leetcode_username', sa.String(), nullable=False),
    sa.Column('leetcode_username_key', sa.String(), nullable=False),
    sa.Column('leetcode_internal_id', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_user_id')
    )
    op.create_index(op.f('ix_leetcode_links_leetcode_username_key'), 'leetcode_links', ['leetcode_username_key'], unique=False)
    op.create_table('leetcode_role_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', 'role_id', name='uq_leet_role_grants_guild_user_role')
    )
    op.create_index(op.f('ix_leetcode_role_grants_expires_at'), 'leetcode_role_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_leetcode_role_grants_guild_id'), 'leetcode_role_grants', ['guild_id'], unique=False)
    op.add_column('guild_config', sa.Column('leetcode_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guild_config', sa.Column('leetcode_reward_role_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('leetcode_solved_total', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('leetcode_streak', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('leetcode_last_solve_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leetcode_last_solve_date')
    op.drop_column('users', 'leetcode_streak')
    op.drop_column('users', 'leetcode_solved_total')
    op.drop_column('guild_config', 'leetcode_reward_role_id')
    op.drop_column('guild_config', 'leetcode_channel_id')
    op.drop_index(op.f('ix_leetcode_role_grants_guild_id'), table_name='leetcode_role_grants')
    op.drop_index(op.f('ix_leetcode_role_grants_expires_at'), table_name='leetcode_role_grants')
    op.drop_table('leetcode_role_grants')
    op.drop_index(op.f('ix_leetcode_links_leetcode_username_key'), table_name='leetcode_links')
    op.drop_table('leetcode_links')
    op.drop_index(op.f('ix_leetcode_assignments_guild_id'), table_name='leetcode_assignments')
    op.drop_index(op.f('ix_leetcode_assignments_discord_user_id'), table_name='leetcode_assignments')
    op.drop_table('leetcode_assignments')
    # ### end Alembic commands ###
