"""initial schema

Revision ID: 39a036b2e6c4
Revises: 
Create Date: 2026-05-22 10:26:48.699532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a036b2e6c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level_up_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leaderboard_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leaderboard_message_id', sa.BigInteger(), nullable=True),
    sa.Column('progsuvian_role_id', sa.BigInteger(), nullable=True),
    sa.Column('xp_blacklist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('channel_multipliers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('role_multipliers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('role_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'level', name='uq_role_rewards_guild_level')
    )
    op.create_index(op.f('ix_role_rewards_guild_id'), 'role_rewards', ['guild_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voice_xp_total', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('text_xp_total', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_users_guild_user')
    )
    op.create_index(op.f('ix_users_guild_id'), 'users', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guild_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_rewards_guild_id'), table_name='role_rewards')
    op.drop_table('role_rewards')
    op.drop_table('guild_config')
    # ### end Alembic commands ###
